name: 'build'

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v1.2.0
    - name: Install yarn dependencies
      run: yarn install --frozen-lockfile
    - name: Lint code
      run: yarn lint
    - name: Build code
      run: yarn build
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@1.0.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true